# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52797d4d787fbeeb4e6376b4a6ace63e383089c51892f8000dfefc50addd8170ac0b626b4a5398b74a39398072272a4cdb087d36f566176fb57143f7fa857e42

test:
  secret_key_base: f83d1dded4d5e514e4a42862b41f0ebf4fa8d74b8fa3a62b4e2a51471266cb32da5ac1e4527cab0bc3ef10b49471f6527187af73a0026c070c0b9b0a20847b74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
